name: MKV to M3U8 Conversion

on:
  workflow_dispatch:  # Manual trigger

jobs:
  convert:
    runs-on: ubuntu-latest

    steps:
      # 1. Checkout repository
      - name: Checkout repository
        uses: actions/checkout@v3
        with:
          persist-credentials: false
          fetch-depth: 0

      # 2. Install ffmpeg
      - name: Install ffmpeg
        run: |
          sudo apt-get update
          sudo apt-get install -y ffmpeg

      # 3. Run conversion script
      - name: Convert MKV to HLS
        run: |
          # Output folder (HLS standard)
          OUTPUT_FOLDER="zebra"
          mkdir -p "$OUTPUT_FOLDER"
          
          # Input MKV URL (replace with your URL)
          INPUT_URL="https://cdn.telugudub.store/Zebra_(2024)_Telugu_720p.mkv"
          
          # Output M3U8 path inside the folder
          OUTPUT_PATH="$OUTPUT_FOLDER/video.m3u8"
          
          # Convert MKV to HLS
          ffmpeg -i "$INPUT_URL" -sn \
                 -c:v copy -c:a copy \
                 -start_number 0 -hls_time 10 -hls_list_size 0 -f hls "$OUTPUT_PATH"

          echo "Conversion complete: $OUTPUT_PATH"

      # 4. Commit and push the HLS folder
      - name: Commit and push results
        env:
          GH_PAT: ${{ secrets.GH_PAT }}
        run: |
          git config --global user.name "pothabattulavinod"
          git config --global user.email "vinodyadavpothabattula666@gmail.com"

          # Stage HLS folder
          git add zebra

          # Commit only if there are changes
          if ! git diff-index --quiet HEAD; then
            git commit -m "Add HLS conversion output [skip ci]"
          else
            echo "No changes to commit"
          fi

          # Set remote with PAT
          git remote remove origin
          git remote add origin https://x-access-token:${GH_PAT}@github.com/pothabattulavinod/mer.git

          # Push changes
          git push origin HEAD:main
