name: RC Transaction Check

on:
  workflow_dispatch:  # manual trigger

jobs:
  run-check:
    runs-on: ubuntu-latest

    steps:
      # 1. Checkout repo
      - uses: actions/checkout@v3

      # 2. Set up Python
      - uses: actions/setup-python@v4
        with:
          python-version: '3.11'

      # 3. Install dependencies
      - run: |
          python -m pip install --upgrade pip
          pip install requests beautifulsoup4

      # 4. Run your script
      - run: python check_transactions.py

      # 5. Commit and push using GH_PAT
      - name: Commit and push results
        env:
          GH_PAT: ${{ secrets.GH_PAT }}
        run: |
          git config --global user.name "pothabattulavinod"
          git config --global user.email "vinodyadavpothabattula666@gmail.com"
          git add 10trns_current.json
          git commit -m "Update RC transaction results [skip ci]" || echo "No changes to commit"
          git push https://x-access-token:$GH_PAT@github.com/${{ github.repository }}.git HEAD:main
