name: RC Transaction Check

on:
  workflow_dispatch:  # manual trigger

jobs:
  run-check:
    runs-on: ubuntu-latest

    steps:
      # 1. Checkout the repository
      - uses: actions/checkout@v3

      # 2. Set up Python
      - uses: actions/setup-python@v4
        with:
          python-version: '3.11'

      # 3. Install dependencies
      - run: |
          python -m pip install --upgrade pip
          pip install requests beautifulsoup4

      # 4. Run the RC transaction script
      - run: python check_transactions.py

      # 5. Commit and push results using GH_PAT
      - name: Commit and push results
        env:
          GH_PAT: ${{ secrets.GH_PAT }}   # Make sure this secret exists
        run: |
          # Configure Git
          git config --global user.name "pothabattulavinod"
          git config --global user.email "vinodyadavpothabattula666@gmail.com"
          
          # Stage changes
          git add 10trns_current.json
          
          # Commit changes if there are any
          git commit -m "Update RC transaction results [skip ci]" || echo "No changes to commit"
          
          # Update remote URL to use PAT
          git remote set-url origin https://x-access-token:$GH_PAT@github.com/pothabattulavinod/mer.git
          
          # Push to main branch
          git push origin main
